### ISSUE TITLE
dscribe setup broken with py 3.10.1?

### ISSUE THREAD

**Issue by ardunn** [SINGROUP/dscribe#79]
Seems like an upstream llvm-lite requirement does not work on py 3.10.1?

My system is 

- Macbook Pro 2017
- Python 3.10.1
- MacOS Big Sur 11.6, 
- Installing from within a virtual environment, not via conda

Tried installing updated llvm via homebrew but that didn't work

Stacktrace is:
```
$: pip install --upgrade dscribe
Collecting dscribe
  Downloading dscribe-1.2.1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 393 kB/s            
  Preparing metadata (setup.py) ... done
Collecting pybind11>=2.4
  Using cached pybind11-2.9.0-py2.py3-none-any.whl (210 kB)
Requirement already satisfied: numpy in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from dscribe) (1.22.0)
Requirement already satisfied: scipy in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from dscribe) (1.7.3)
Collecting ase>=3.19.0
  Using cached ase-3.22.1-py3-none-any.whl (2.2 MB)
Requirement already satisfied: scikit-learn in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from dscribe) (1.0.1)
Requirement already satisfied: joblib>=1.0.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from dscribe) (1.1.0)
Collecting sparse
  Using cached sparse-0.13.0-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: matplotlib>=3.1.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from ase>=3.19.0->dscribe) (3.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from scikit-learn->dscribe) (3.0.0)
Collecting numba>=0.49
  Using cached numba-0.51.2.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: fonttools>=4.22.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (4.28.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (1.3.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (9.0.0)
Requirement already satisfied: packaging>=20.0 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from matplotlib>=3.1.0->ase>=3.19.0->dscribe) (0.11.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from numba>=0.49->sparse->dscribe) (58.1.0)
Requirement already satisfied: six>=1.5 in /Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.0->ase>=3.19.0->dscribe) (1.16.0)
Building wheels for collected packages: dscribe, numba, llvmlite
  Building wheel for dscribe (setup.py) ... done
  Created wheel for dscribe: filename=dscribe-1.2.1-cp310-cp310-macosx_10_9_universal2.whl size=1180272 sha256=72f002d4a9f448ae1f68213684ba2d357af01f4c7e50d6095658aa97e969a9c8
  Stored in directory: /Users/ardunn/Library/Caches/pip/wheels/97/66/d1/952924ba75d63acda8155b6e913478f6c31920034505249cc1
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/numba_35e05a43186a463b9b06133c57882232/setup.py'"'"'; __file__='"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/numba_35e05a43186a463b9b06133c57882232/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-wheel-08rqeoxx
       cwd: /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/numba_35e05a43186a463b9b06133c57882232/
  Complete output (794 lines):
  TBB not found
  OpenMP not found
  running bdist_wheel
  running build
  got version from file /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/numba_35e05a43186a463b9b06133c57882232/numba/_version.py {'version': '0.51.2', 'full': '9d570961590c09a1eba748c9c37e91d1224fc9ad'}
  running build_py
  creating build
  creating build/lib.macosx-10.9-universal2-3.10
  creating build/lib.macosx-10.9-universal2-3.10/numba
  copying numba/_version.py -> build/lib.macosx-10.9-universal2-3.10/numba
  copying numba/__init__.py -> build/lib.macosx-10.9-universal2-3.10/numba

...

  <<many similar lines here>>
...

  running build_ext
  building 'numba._dynfunc' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  INFO: C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g
  
  creating build/temp.macosx-10.9-universal2-3.10
  creating build/temp.macosx-10.9-universal2-3.10/numba
  INFO: compile options: '-I/Users/ardunn/alex/lbl/projects/common_env/matminer_env/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c'
  extra options: '-g'
  INFO: clang: numba/_dynfuncmod.c
  INFO: clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-3.10/numba/_dynfuncmod.o -o build/lib.macosx-10.9-universal2-3.10/numba/_dynfunc.cpython-310-darwin.so
  building 'numba._dispatcher' extension
  INFO: C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g
  
  creating build/temp.macosx-10.9-universal2-3.10/numba/core
  creating build/temp.macosx-10.9-universal2-3.10/numba/core/typeconv
  INFO: compile options: '-I/Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages/numpy/core/include -I/Users/ardunn/alex/lbl/projects/common_env/matminer_env/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c'
  INFO: clang: numba/_dispatcher.c
  INFO: clang: numba/_dispatcherimpl.cpp
  INFO: clang: numba/_hashtable.c
  INFO: clang: numba/_typeof.c
  numba/_dispatcher.c:26:13: error: no member named 'use_tracing' in 'struct _ts'
      tstate->use_tracing = 0;
      ~~~~~~  ^
  numba/_dispatcher.c:28:13: error: no member named 'use_tracing' in 'struct _ts'
      tstate->use_tracing = ((tstate->c_tracefunc != NULL)
      ~~~~~~  ^
  numba/_dispatcher.c:303:17: error: no member named 'use_tracing' in 'struct _ts'
      if (tstate->use_tracing && tstate->c_profilefunc)
          ~~~~~~  ^
  numba/_dispatcher.c:512:13: error: no member named 'use_tracing' in 'struct _ts'
      if (ts->use_tracing && ts->c_profilefunc) {
          ~~  ^
  4 errors generated.
  INFO: clang: numba/core/typeconv/typeconv.cpp
  error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/ardunn/alex/lbl/projects/common_env/matminer_env/lib/python3.10/site-packages/numpy/core/include -I/Users/ardunn/alex/lbl/projects/common_env/matminer_env/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c numba/_dispatcher.c -o build/temp.macosx-10.9-universal2-3.10/numba/_dispatcher.o" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"'; __file__='"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-wheel-li0v_c6k
       cwd: /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/
  Complete output (26 lines):
  running bdist_wheel
  /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 191, in <module>
      main()
    File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 185, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built dscribe
Failed to build numba llvmlite
Installing collected packages: llvmlite, numba, sparse, pybind11, ase, dscribe
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"'; __file__='"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-record-79x0xv3w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ardunn/alex/lbl/projects/common_env/matminer_env/include/site/python3.10/llvmlite
         cwd: /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ardunn/alex/lbl/projects/common_env/matminer_env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"'; __file__='"'"'/private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-install-w4b_7e81/llvmlite_d24e9fd40b17403e828fc96783d76705/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4z/3vrw2wq10kzfh29c4x35qk3m0000gp/T/pip-record-79x0xv3w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ardunn/alex/lbl/projects/common_env/matminer_env/include/site/python3.10/llvmlite Check the logs for full command output.
```

**Comment by lauri-codes** [comment]
Hi @ardunn!

We use the `sparse`-library for our sparse-matrices, which seems to have a dependency on `numba`, which has a dependency on `llvmlite`, which, depending on the version, might not yet support Python 3.10.

I was able to solve this issue on my machine (Ubuntu 20.04, python 3.10 + python3-10-dev package) by:

1. Update pip: `pip install --update pip`
2. Install llvmlite version that supports python3.10: `pip install llvmlite==0.38.0`
3. Then install dscribe: `pip install dscribe`

Hope this helps!

**Comment by lauri-codes** [comment]
I have confirmed that our test pipeline does now run through correctly for python 3.10. If you still experience problems, re-open this issue.
